# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: rdlsolutions/hobot
  tag: "v1.0.9-f6b6721"
  arch: "amd64"
  os: linux
secret:
  name: "hobot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
